# 
# Week 3, Class 5
# Numpy and list, more numpy

In [1]:
import numpy as np
import sys
a_l = [1,2,3]
a_l

[1, 2, 3]

In [2]:
a_l = ['a',1]
a_l

['a', 1]

In [22]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a.dtype

dtype('int32')

In [23]:
print(a*3) # Item wise multiplication
# Look into 3 C 2 - 1

[3 6 9]


In [10]:
print(a_l *3) # List multiplication

['a', 1, 'a', 1, 'a', 1]


In [19]:
size_list = sys.getsizeof(1)*len(a_l)
size_nu = a.itemsize*a.size
print(f"the size of same values of lists is {size_list} and array is {size_nu}")

the size of same values of lists is 56 and array is 12


In [20]:
size_list

56

In [21]:
size_nu = a.itemsize*a.size
size_nu

12

In [26]:
a=[[1,2],[3,4],[3,6]]
a

[[1, 2], [3, 4], [3, 6]]

In [28]:
# 3 by 2 array
np.shape(a)

(3, 2)

In [31]:
# Create a array
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a=np.arange(0,10,0.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [37]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [38]:
np.shape(a)

(5,)

In [45]:
a.T
a

array([0, 2, 4, 6, 8])

In [46]:
np.shape(a)

(5,)

In [56]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
a=np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
a=a.T
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Let's perform math functions

In [68]:
a=np.array([1,2,3,4,5,6])

In [70]:
np.max(a)

6

In [71]:
np.min(a)

1

In [72]:
np.sum(a)

21

In [73]:
np.mean(a)

3.5

In [77]:
np.size(a)

6

In [78]:
a=a+1
a

array([2, 3, 4, 5, 6, 7])

In [81]:
a=np.array([1,3,5,7])
b=np.array([2,4,6,8])
c=a+b
c

array([ 3,  7, 11, 15])

In [82]:
c=a*b
c

array([ 2, 12, 30, 56])

In [83]:
np.sqrt(c)

array([1.41421356, 3.46410162, 5.47722558, 7.48331477])

In [84]:
a=np.array([1,2,3,4,5])

In [85]:
a[1]

2

In [86]:
a[0]

1

In [87]:
a[:]

array([1, 2, 3, 4, 5])

In [88]:
a[:1]

array([1])

In [89]:
a[0:2]

array([1, 2])

In [90]:
a[:2]

array([1, 2])

In [91]:
a[-1:]

array([5])

In [92]:
a[1:]

array([2, 3, 4, 5])

In [93]:
a[:-1]

array([1, 2, 3, 4])

In [124]:
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
np.shape(a)

(5, 2)

In [102]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [116]:
a[0:1,0:2]

array([[1, 2]])

In [118]:
a[0:1,0:]
a[0:1,]

array([[1, 2]])

In [119]:
a[3:4,]

array([[7, 8]])

In [120]:
a[3:4,-1]

array([8])

In [127]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [130]:
a=np.array([[1,2,1],[3,4,1],[5,6,1],[7,8,1],[9,10,0]])
a

array([[ 1,  2,  1],
       [ 3,  4,  1],
       [ 5,  6,  1],
       [ 7,  8,  1],
       [ 9, 10,  0]])

In [131]:
a[2:3,]

array([[5, 6, 1]])

In [132]:
a[2:3,-1]

array([1])

# Filter Rows

In [133]:
a

array([[ 1,  2,  1],
       [ 3,  4,  1],
       [ 5,  6,  1],
       [ 7,  8,  1],
       [ 9, 10,  0]])

In [135]:
np.where(a<3)

(array([0, 0, 0, 1, 2, 3, 4], dtype=int64),
 array([0, 1, 2, 2, 2, 2, 2], dtype=int64))

In [144]:
a=np.array([1,2,3,4,5,10])
np.where(a<3)

(array([0, 1], dtype=int64),)

In [140]:
np.where(a>3)

(array([3, 4, 5], dtype=int64),)

In [141]:
a[np.where(a>3)]

array([4, 5, 6])

In [145]:
a

array([ 1,  2,  3,  4,  5, 10])

In [147]:
a[0:1]=100
a

array([100,   2,   3,   4,   5,  10])

In [149]:
a[2:5]=120
a

array([100,   2, 120, 120, 120,  10])

In [157]:
a=np.array([[1,2,1],[3,4,1],[5,6,1],[7,8,1],[9,10,0]])
a

array([[ 1,  2,  1],
       [ 3,  4,  1],
       [ 5,  6,  1],
       [ 7,  8,  1],
       [ 9, 10,  0]])

In [158]:
a[0:5,2:3]=100

In [159]:
a

array([[  1,   2, 100],
       [  3,   4, 100],
       [  5,   6, 100],
       [  7,   8, 100],
       [  9,  10, 100]])

In [160]:
a[:,-1]=0
a

array([[ 1,  2,  0],
       [ 3,  4,  0],
       [ 5,  6,  0],
       [ 7,  8,  0],
       [ 9, 10,  0]])

In [169]:
a.astype(float)

array([[ 1.,  2.,  0.],
       [ 3.,  4.,  0.],
       [ 5.,  6.,  0.],
       [ 7.,  8.,  0.],
       [ 9., 10.,  0.]])

In [170]:
a[2,2]=np.nan
a

ValueError: cannot convert float NaN to integer

In [171]:
np.isnan(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [172]:
np.isinf(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

# Homework replace null with mean of array
# Create a 9x9 matrix of sudoku, load the data to pandas 
# Convert the pandas to NumPy (df.values)
# Replace NULL's with zeros
# Strategy 1: replace zero with correct value

In [176]:
a=[1,2,3,4,5,6,7,8,0]
b=[1,2,3,4,5,6,7,8,9]
np.setdiff1d(b,a)

array([9])