# Funtions
# funtions main reason is reusablity 
# scope - put together funtions at a slower pace
# next week; play with data sets with funtions we create


** Important elements of a functions
** 1) Name, 2) parameters (or arguments) 3) logic 4) output value(s)

In [178]:
# funtion to add two numbers
def addTwoNumbers(x,y):
    c=x+y
    return c

In [179]:
z=addTwoNumbers(333,77)

In [180]:
z

410

In [181]:
def addTwoNumbersV2(x,y):
    return x+y

In [182]:
y=addTwoNumbersV2(333,77)

In [183]:
y

410

In [184]:
# I want to perform 4 math funtions, 1, I would like to add two numbers
def fourMathFuntions(x,y,typ):
    if typ=='1':
        c=x+y
    elif typ=='2':
        c=x-y
    elif typ=='3':
        c=x*y
    elif typ=='4':
        c=x/y
    else:
        c='Enter the right value dummy!'
    return c

In [185]:
print(fourMathFuntions(10,20,typ='5'))

Enter the right value dummy!


In [186]:
import pandas as pd
import numpy as np
a=2
b=[1,2,3]
c=np.array([1,2,3])
d=pd.DataFrame([1,2,3,4])

In [187]:
type(d)

pandas.core.frame.DataFrame

In [188]:
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'int'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


In [189]:
# The goal is convert whatever you pass as argument into an numpy array
# Input parameters -variable (int, list, numpy, panads)
# Output we are expecting is numpy array
# Logic first I need to what data type the variable is
def convertToNumpy(x):
    if type(x)==int:
        c=np.array(x)
    elif type(x)==list:
        c=np.array(x)
    elif type(x)==pd.core.frame.DataFrame:
        c=d.values
    else:
        c=x
    return c

In [190]:
d.values

array([[1],
       [2],
       [3],
       [4]], dtype=int64)

In [191]:
convertToNumpy(c)

array([1, 2, 3])

In [192]:
np.array(a)

array(2)

In [193]:
import os

In [293]:
path = 'https://raw.githubusercontent.com/vikrambj2019/basic/master/Data/'
filename_read=os.path.join(path,"twobytwo.csv")
df=pd.read_csv(filename_read,na_values=['NA','?'])

In [294]:
df

C1   C2   C3   C4
0  3.0  4.0  1.0  NaN
1  NaN  2.0  NaN  NaN
2  NaN  NaN  2.0  NaN
3  NaN  1.0  4.0  3.0

In [84]:
3,4,1,2
1,2,3,4
4,3,2,1
2,1,4,3

(2, 1, 4, 3)

In [199]:
list

[1, 2, 3, 4, 0]

In [200]:
ls=df.values

In [201]:
ls

array([[ 3.,  4.,  1., nan],
       [nan,  2., nan, nan],
       [nan, nan,  2., nan],
       [nan,  1.,  4.,  3.]])

In [202]:
np.argwhere(np.isnan(ls))

array([[0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]], dtype=int64)

In [203]:
ls[np.isnan(ls)]=0

In [204]:
ls

array([[3., 4., 1., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [205]:
np.argwhere(ls==0)

array([[0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]], dtype=int64)

In [206]:
ls[:0]

array([], shape=(0, 4), dtype=float64)

In [207]:
ls[0] #this is the row

array([3., 4., 1., 0.])

In [208]:
ls[:,2] # gets column values in np

array([1., 0., 2., 4.])

In [209]:
ls[0:2,2:4] # this is the array

array([[1., 0.],
       [0., 0.]])

In [211]:
row=a[0][0]
col=a[0][1]

TypeError: 'int' object is not subscriptable

In [212]:
a=np.argwhere(ls==0)

In [213]:
a[0][1]

3

In [214]:
if a[0][0] in (0,1):
    row_sq=0
else:
    row_sq=2
row_sq

0

In [215]:
if a[0][1] in (0,1):
    col_sq=0
else:
    col_sq=2
col_sq

2

In [216]:
ls[row_sq:row_sq+2,col_sq:col_sq+2] # the +2 is to make sure you're pulling in the two rows or two columns

array([[1., 0.],
       [0., 0.]])

In [217]:
ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4)

array([[1., 0., 0., 0.]])

In [218]:
row

0

In [219]:
ls[row]

array([3., 4., 1., 0.])

In [220]:
a=np.append(ls[row].tolist(),[ls[:,col].tolist(),ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist()])

In [221]:
a

array([3., 4., 1., 0., 0., 0., 0., 3., 1., 0., 0., 0.])

In [222]:
list1=[1,2,3,4,0]
b=set(list1).difference(a)
b

{2}

In [237]:
ls=df.values # Convert panadas to numpy array
ls[np.isnan(ls)]=0 # Convert Nulls to zeros
a=np.argwhere(ls==0) # Saving the address locations of all zeros in array called "a"

# a holds the address of all my zeros

row=a[0][0] # Will give me the row of the first zero address
col=a[0][1] # Will give me the column of the first zero address
ls[row] # Will give me the array of the row
ls[:,col] # Will give me the array of the column

if a[0][0] in (0,1): # (in (0,1) is saying if a[0][0] is = to 0 OR 1 preform the first part of the if statement ELSE then next)
    row_sq=0
else:
    row_sq=2
row_sq

if a[0][1] in (0,1): # 
    col_sq=0
else:
    col_sq=2
col_sq

ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten() # changing from 2x2 to 1x4 and flatten it out

a=np.append(ls[row].tolist(),[ls[:,col].tolist(),ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist()])
# Showing the unique values that are listed in all 3 arrays ^

list1=[1,2,3,4,0] # This is setting the list of all the values that are possible outcomes
b=set(list1).difference(a) 
ls[row,col]=list(b)[0] # Fills in the value with the value that was missing from the set 2 in this case


In [238]:
ls

array([[3., 4., 1., 2.],
       [1., 2., 3., 0.],
       [0., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [235]:
ls[row,col]=list(b)[0]

In [239]:
list(b)

[3]

In [280]:
def sudokuTwoByTwoStrategy1(df):
    ls=df.values # Convert panadas to numpy array
    ls[np.isnan(ls)]=0 # Convert Nulls to zeros
    a=np.argwhere(ls==0) # Saving the address locations of all zeros in array called "a"
    for i in range(len(a)):
        b=a[i]
    # a holds the address of all my zeros

        row=b[0] # Will give me the row of the first zero address
        col=b[1] # Will give me the column of the first zero address
        #ls[row] # Will give me the array of the row
        #ls[:,col] # Will give me the array of the column

        if a[i][0] in (0,1): # (in (0,1) is saying if a[0][0] is = to 0 OR 1 preform the first part of the if statement ELSE then next)
            row_sq=0
        else:
            row_sq=2
        row_sq

        if a[i][1] in (0,1): # 
            col_sq=0
        else:
            col_sq=2
        col_sq

        ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten() # changing from 2x2 to 1x4 and flatten it out

        a=np.append(ls[row].tolist(),[ls[:,col].tolist(),ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist()])
        # Showing the unique values that are listed in all 3 arrays ^

        list1=[1,2,3,4,0] # This is setting the list of all the values that are possible outcomes
        b=set(list1).difference(a) 
        ls[row,col]=list(b)[0] # Fills in the value with the value that was missing from the set 2 in this case

    return ls

In [281]:
ls=sudokuTwoByTwoStrategy1(df)
ls

IndexError: invalid index to scalar variable.

In [278]:
ls=df.values

In [279]:
ls

array([[3., 4., 1., 2.],
       [1., 2., 3., 4.],
       [4., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [264]:
ls[np.isnan(ls)]=0

In [265]:
a=np.argwhere(ls==0)

In [266]:
a

array([[1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]], dtype=int64)

In [302]:
def sudokuTwoByTwoStrategy1(df):
    ls=df.values # Convert panadas to numpy array
    ls[np.isnan(ls)]=0 # Convert Nulls to zeros
    a=np.argwhere(ls==0) # Saving the address locations of all zeros in array called "a"
    for i in range(len(a)):
        b=a[i]
    # a holds the address of all my zeros

        row=b[0] # Will give me the row of the first zero address
        col=b[1] # Will give me the column of the first zero address
        #ls[row] # Will give me the array of the row
        #ls[:,col] # Will give me the array of the column

        if row in (0,1): # (in (0,1) is saying if a[0][0] is = to 0 OR 1 preform the first part of the if statement ELSE then next)
            row_sq=0
        else:
            row_sq=2
        row_sq

        if col in (0,1): # 
            col_sq=0
        else:
            col_sq=2
        col_sq

        ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten() # changing from 2x2 to 1x4 and flatten it out

        c=np.append(ls[row].tolist(),[ls[:,col].tolist(),ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist()])
        # Showing the unique values that are listed in all 3 arrays ^

        list1=[1,2,3,4,0] # This is setting the list of all the values that are possible outcomes
        d=set(list1).difference(c)
        ls[row,col]=list(d)[0] # Fills in the value with the value that was missing from the set 2 in this case

    return ls

In [303]:
ls=sudokuTwoByTwoStrategy1(df)
ls

array([[3., 4., 1., 2.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.],
       [2., 1., 4., 3.]])

In [301]:
import sudokuStrat1.py

ModuleNotFoundError: No module named 'sudokuStrat1.py'; 'sudokuStrat1' is not a package